/*
 * Copyright (c) 2020.
 * Dimitrios Papazisis
 * This Software is to be used for educational purposes only.
 * All rights Reserved.
 */

package com.dpapazisis.librarian.categories;

import java.io.Serializable;
import java.util.Objects;

/**
 * DeweyCode class reflect and simplified implementation of the Dewey Decimal system by me
 * for demonstrating purposes and <tt>should not be used as production data type</tt>
 * <p>
 * The code is generated by using the basic 3 digit
 * of the main categories of the Dewey system and the copy number
 * of a document as the decimal part.
 * Then 3 capital letters are added to the end generated by info taken from the document
 * </p>
 *
 * @author Dimitrios Papazisis
 */
public class DeweyCode implements Serializable {
    private final String category;
    private final String referenceCode;

    /**
     * Constructor for a DeweyCOde object
     * Should be use with collaboration of the {@link Classifier} class for code generation
     *
     * @param category      {@link String} the category name
     * @param referenceCode {@link String} the code generated
     */
    protected DeweyCode(String category, String referenceCode) {
        this.category = category;
        this.referenceCode = referenceCode;
    }

    /**
     * Returns the name of the category assigned
     *
     * @return {@link String} the name of the category
     */
    public String getCategory() {
        return category;
    }

    /**
     * Returns the reference code assigned to the object
     *
     * @return {@link String} the reference code
     */
    public String getCode() {
        return referenceCode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DeweyCode deweyCode = (DeweyCode) o;
        return getCategory().equals(deweyCode.getCategory()) && getCode().equals(deweyCode.getCode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCategory(), getCode());
    }

    @Override
    public String toString() {
        return "{" + "category: '" + category + '\'' +
                ", referenceCode: '" + referenceCode + '\'' + "}";
    }
}
